routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home;
use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Login;
use App\Http\Controllers\Logout;


Route::get('/', [Home::class, 'index'])->name('index');
Route::get('/login', [Login::class, 'index'])->name('login');
Route::post('/login', [Login::class, 'cek'])->name('login.cek');

Route::group([
    'prefix' => 'app',
    'as' => 'app.',
    'namespace' => 'App',
    'middleware' => ['user'],
], function () {

	require_once(__DIR__.'/master.php');

	Route::get('/logout', [Logout::class, 'index'])->name('logout');
	Route::get('/', [Dashboard::class, 'index'])->name('index');
//==================================================================

	Route::group([
    'prefix' => 'transaksi',
    'as' => 'transaksi.',
    'namespace' => 'Transaksi',
	], function ()
	{
			

		Route::group([
		    'prefix' => 'sosialisasi_kegiatan',
		    'as' => 'sosialisasi_kegiatan.',
		    'namespace' => 'Sosialisasi_kegiatan',
		], function (){
			Route::get('/', [\App\Http\Controllers\Sosialisasi_kegiatan::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'pendaftaran',
		    'as' => 'pendaftaran.',
		    'namespace' => 'Pendaftaran',
		], function (){
			Route::get('/', [\App\Http\Controllers\Pendaftaran::class, 'index'])->name('index');
			Route::get('/rekap_tpq', [\App\Http\Controllers\Pendaftaran::class, 'rekap_tpq'])->name('rekap_tpq');
			Route::get('/edit', [\App\Http\Controllers\Pendaftaran::class, 'edit'])->name('edit');
			Route::get('/kwitansi', [\App\Http\Controllers\Pendaftaran::class, 'kwitansi'])->name('kwitansi');
		});


		Route::group([
		    'prefix' => 'validasi_data_peserta',
		    'as' => 'validasi_data_peserta.',
		    'namespace' => 'Validasi_data_peserta',
		], function (){
			Route::get('/', [\App\Http\Controllers\Validasi_data_peserta::class, 'index'])->name('index');
		});

		Route::group([
		    'prefix' => 'pembuatan_jadwal',
		    'as' => 'pembuatan_jadwal.',
		    'namespace' => 'Pembuatan_jadwal',
		], function (){
			Route::get('/', [\App\Http\Controllers\Pembuatan_jadwal::class, 'index'])->name('index');
		});

		Route::group([
		    'prefix' => 'pembuatan_kartu_peserta',
		    'as' => 'pembuatan_kartu_peserta.',
		    'namespace' => 'Pembuatan_kartu_peserta',
		], function (){
			Route::get('/', [\App\Http\Controllers\Pembuatan_kartu_peserta::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'teknikal_meeting',
		    'as' => 'teknikal_meeting.',
		    'namespace' => 'Teknikal_meeting',
		], function (){
			Route::get('/', [\App\Http\Controllers\Teknikal_meeting::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'buku_daftar_hadir',
		    'as' => 'buku_daftar_hadir.',
		    'namespace' => 'Buku_daftar_hadir',
		], function (){
			Route::get('/', [\App\Http\Controllers\Buku_daftar_hadir::class, 'index'])->name('index');
		});

		Route::group([
		    'prefix' => 'buku_rekap_nilai',
		    'as' => 'buku_rekap_nilai.',
		    'namespace' => 'Buku_rekap_nilai',
		], function (){
			Route::get('/', [\App\Http\Controllers\Buku_rekap_nilai::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'simulasi_imtas',
		    'as' => 'simulasi_imtas.',
		    'namespace' => 'Simulasi_imtas',
		], function (){
			Route::get('/', [\App\Http\Controllers\Simulasi_imtas::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'pelaksanaan_imtas',
		    'as' => 'pelaksanaan_imtas.',
		    'namespace' => 'Pelaksanaan_imtas',
		], function (){
			Route::get('/', [\App\Http\Controllers\Pelaksanaan_imtas::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'evaluasi_hasil_imtas',
		    'as' => 'evaluasi_hasil_imtas.',
		    'namespace' => 'Evaluasi_hasil_imtas',
		], function (){
			Route::get('/', [\App\Http\Controllers\Evaluasi_hasil_imtas::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'pembuatan_lpj',
		    'as' => 'pembuatan_lpj.',
		    'namespace' => 'Pembuatan_lpj',
		], function (){
			Route::get('/', [\App\Http\Controllers\Pembuatan_lpj::class, 'index'])->name('index');
		});


		Route::group([
		    'prefix' => 'data_imtihan',
		    'as' => 'data_imtihan.',
		    'namespace' => 'Data_imtihan',
		], function (){
			Route::get('/', [\App\Http\Controllers\Data_imtihan::class, 'index'])->name('index');
		});



	});

});

app/Http/Controllers/Pendaftaran.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Pendaftaran extends Controller
{

	public function konstanta()
	{
		if(session('logged_in.id_korcab')){ // jika user login sebagai korcab

    		$tipe_user = 'id_korcab';
    		$where = [
    			'id_korcab' => session('logged_in.id_korcab')
    		];
    		$template = 'pendaftaran.korcab';
    		$template_rekap_tpq = 'pendaftaran.korcab_rekap_tpq';

    	}else if(session('logged_in.id_korcam')){ // jika user login sebagai korcam

    		$tipe_user = 'id_korcam';
    		$where = [
    			'id_korcam' => session('logged_in.id_korcam')
    		];
    		$template = 'pendaftaran.korcam';
    		$template_rekap_tpq = 'pendaftaran.korcam_rekap_tpq';

    	}

    	$data = [
    		'tipe_user' => $tipe_user,
    		'where' => $where,
    		'template' => $template,
    		'template_rekap_tpq' => $template_rekap_tpq,
    	];
    	return (object) $data;
	}



    public function index()
    {
    	$data = \App\Models\T_periode::Aktif()->with('t_peserta.m_korcam')->where($this->konstanta()->where)->first();
    	return view($this->konstanta()->template)->with([
            'data' => $data,
            'tipe_user' => $this->konstanta()->tipe_user,
        ]);
    }

    public function rekap_tpq()
    {
    	$data = \App\Models\T_periode::Aktif()
    			->with('t_peserta.t_tpq','t_peserta.m_korcam','t_peserta.t_tpq.t_santri')
    			->where($this->konstanta()->where)->first();
    	return view($this->konstanta()->template_rekap_tpq)->with([
            'data' => $data,
            'tipe_user' => $this->konstanta()->tipe_user,
        ]);
    }

    public function edit()
    {
    	if(!request()->filled('id_periode') or !request()->filled('id_korcam') or !is_numeric(request('id_korcam'))){
    		abort(404);
    	}

    	$old = \App\Models\M_agenda_kegiatan::where([
    		'id_korcam' => request('id_korcam')
    	])->firstOrFail();

		return view("agenda.edit")->with([
            'old' => $old
        ]);
    }

}

resources/views/pendaftaran/korcab.blade.php
@extends('layout.index')




@section('content')


<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Home</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Home</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-4">
          
          <div class="card">
            <div class="card-header bg-primary">
              <h3 class="card-title">Rekap</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
					<table class="table table-bordered table-hover table-sm table-striped">
						<thead>
								<tr class="">
								  <th class="text-center">No</th>
								  <th class="text-center">Korcam</th>
								  <th class="text-center">TPQ</th>
								  <th class="text-center">Santri</th>
								  <th class="text-center">Infaq</th>
								  <th class="text-center">Menu</th>
								</tr>
							</thead>
							<tbody>
							@php $i = 1; @endphp
							@foreach($data->t_peserta as $row)
								<tr>
									<td class="text-center">{{$i++}}</td>
									<td>{{$row->m_korcam->nama_korcam}}</td>
									<td class="text-center">25</td>
									<td class="text-center">344</td>
									<td class="text-right">24.080.000</td>
									<td class="text-center">
										<a data-toggle="tooltip" data-placement="top" title="edit" href="{{route('app.transaksi.pendaftaran.edit', ['korcam' => $row->id_korcam, 'id_periode' => $row->id_periode])}}" class="btn btn-xs btn-warning" data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-edit"></i></a>
										<a data-toggle="tooltip" data-placement="top" title="kwitansi" href="{{route('app.transaksi.pendaftaran.kwitansi')}}" class="btn btn-xs btn-primary" data-toggle="tooltip" data-original-title="Kwitansi"><i class="fa fa-credit-card"></i></a>
									</td>
								</tr>
							@endforeach
							</tbody>
							<thead>
								<tr>
								  <th class="text-center" colspan="2">Jumlah</th>
								  <th class="text-center">111</th>
								  <th class="text-center">1.313</th>
								  <th class="text-right">91.910.000</th>
								  <th class=""></th>
								</tr>
							</thead>
						</table>

				</div>
                </div>
               
            </div>
            <!-- /.card-body -->
          </div>
         



        <div class="col-md-8">
          
          <div class="card">
            <div class="card-header bg-primary">
              <h3 class="card-title">Rekap</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                	<a href="{{ route('app.transaksi.pendaftaran.index') }}" class="btn btn-{{\Route::currentRouteName() == 'app.transaksi.pendaftaran.index' ? 'primary' : 'default'}} mb-3"><i class="fas fa-list"></i> Rekap Korcam</a>&nbsp;&nbsp;
                	<a href="{{ route('app.transaksi.pendaftaran.rekap_tpq') }}" class="btn btn-{{\Route::currentRouteName() == 'app.transaksi.pendaftaran.rekap_tpq' ? 'primary' : 'default'}} mb-3"><i class="fas fa-list"></i> Rekap TPQ</a>
                	<p></p><br>
                	<table class="table table-bordered table-sm table-striped">
						<thead>
							<tr>
							  <th class="text-center" rowspan="2">No</th>
							  <th class="text-center" rowspan="2">Korcam</th>
							  <th class="text-center" colspan="2">Lembaga</th>
							  <th class="text-center" colspan="3">Peserta</th>
							  <th class="text-center" rowspan="2">Infaq</th>
							  <th class="text-center" rowspan="2">Waktu</th>
							</tr>
							<tr>
							  <th class="text-center">Jml</th>
							  <th class="text-center">Imtas</th>
							  <th class="text-center">Baru</th>
							  <th class="text-center">Ulang</th>
							  <th class="text-center">Jml</th>
							</tr>
						</thead>
						<tbody>
							@php $i = 1; @endphp
							@foreach($data->t_peserta as $row)
							<tr>
								<td class="text-center">{{$i++}}</td>
								<td>{{$row->m_korcam->nama_korcam}}</td>
								<td class="text-center">30</td>
								<td class="text-center">25</td>
								<td class="text-center">344</td>
								<td class="text-center">0</td>
								<td class="text-center">344</td>
								<td class="text-right">24.080.000</td>
								<td class="text-center">2021-01-25 07:26:39</td>
							</tr>
							@endforeach
						</tbody>
					</table>

                </div>
            </div>
          </div>
        </div>


  </section>
    <!-- /.content -->

				@endsection

resources/views/pendaftaran/korcab_rekap_tpq.blade.php
@extends('layout.index')




@section('content')


<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Home</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Home</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-4">
          
          <div class="card">
            <div class="card-header bg-primary">
              <h3 class="card-title">Rekap</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">

					<table class="table table-bordered table-sm table-striped">
						<thead>
								<tr class="">
								  <th class="text-center">No</th>
								  <th class="text-center">Korcam</th>
								  <th class="text-center">TPQ</th>
								  <th class="text-center">Santri</th>
								  <th class="text-center">Infaq</th>
								  <th class="text-center">Menu</th>
								</tr>
							</thead>
							<tbody>
								@php $i = 1; @endphp
								@foreach($data->t_peserta as $row)
									<tr>
										<td class="text-center">{{$i++}}</td>
										<td>{{$row->m_korcam->nama_korcam}}</td>
										<td class="text-center">25</td>
										<td class="text-center">344</td>
										<td class="text-right">24.080.000</td>
										<td class="text-center">
											<a data-toggle="tooltip" data-placement="top" title="edit" href="{{route('app.transaksi.pendaftaran.edit', ['korcam' => $row->id_korcam])}}" class="btn btn-xs btn-warning" data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-edit"></i></a>
											<a data-toggle="tooltip" data-placement="top" title="kwitansi" href="{{route('app.transaksi.pendaftaran.kwitansi')}}" class="btn btn-xs btn-primary" data-toggle="tooltip" data-original-title="Kwitansi"><i class="fa fa-credit-card"></i></a>
										</td>
									</tr>
								@endforeach
							</tbody>
							<thead>
								<tr>
								  <th class="text-center" colspan="2">Jumlah</th>
								  <th class="text-center">111</th>
								  <th class="text-center">1.313</th>
								  <th class="text-right">91.910.000</th>
								  <th class=""></th>
								</tr>
							</thead>
						</table>

				</div>
                </div>
               
            </div>
            <!-- /.card-body -->
          </div>
         



        <div class="col-md-8">
          
          <div class="card">
            <div class="card-header bg-primary">
              <h3 class="card-title">Rekap</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">

                	<a href="{{ route('app.transaksi.pendaftaran.index') }}" class="btn btn-{{\Route::currentRouteName() == 'app.transaksi.pendaftaran.index' ? 'primary' : 'default'}} mb-3"><i class="fas fa-list"></i> Rekap Korcam</a>&nbsp;&nbsp;
                	<a href="{{ route('app.transaksi.pendaftaran.rekap_tpq') }}" class="btn btn-{{\Route::currentRouteName() == 'app.transaksi.pendaftaran.rekap_tpq' ? 'primary' : 'default'}} mb-3"><i class="fas fa-list"></i> Rekap TPQ</a>
                	<p></p><br>
                	<table class="table table-bordered table-sm table-striped">
						<thead>
							<tr>
							  <th>No</th>
							  <th>Induk</th>
							  <th>Korcam</th>
							  <th>Induk</th>
							  <th>TPQ</th>
							  <th>Alamat</th>
							  <th>Kepala</th>
							  <th>Santri</th>
							  <th>Peserta</th>
							  <th>%</th>
							</tr>
						</thead>
						<tbody>
							@php $i = 1; @endphp

							@foreach($data->t_peserta as $row)

								@foreach($row->t_tpq as $tpq)
								<tr>
									<td class="text-center">{{$i++}}</td>
									<td>{{$row->m_korcam->kode}}</td>
									<td>{{$row->m_korcam->nama_korcam}}</td>
									<td>{{$tpq->induk_tpq}}</td>
									<td>{{$tpq->nama_tpq}}</td>
									<td>{{$tpq->alamat_tpq}}</td>
									<td>{{$tpq->kepala_tpq}}</td>
									<td>{{$tpq->jumlah_santri}}</td>
									<td>{{count($tpq->t_santri)}}</td>
									<td>{{(count($tpq->t_santri) / 100)*$tpq->jumlah_santri}}</td>
								</tr>
								@endforeach

							@endforeach
						</tbody>
					</table>

                </div>
            </div>
          </div>
        </div>


  </section>
    <!-- /.content -->

				@endsection

resources/views/pendaftaran/korcam.blade.php
@extends('layout.index')




@section('content')


<section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Home</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Home</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-4">
          
          <div class="card">
            <div class="card-header bg-primary">
              <h3 class="card-title">Rekap</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
					<table class="table table-bordered table-hover table-sm table-striped">
						<thead>
								<tr class="">
								  <th class="text-center">No</th>
								  <th class="text-center">Korcam</th>
								  <th class="text-center">TPQ</th>
								  <th class="text-center">Santri</th>
								  <th class="text-center">Infaq</th>
								  <th class="text-center">Menu</th>
								</tr>
							</thead>
							<tbody>
							@php $i = 1; @endphp
							@foreach($data->t_peserta as $row)
								<tr>
									<td class="text-center">{{$i++}}</td>
									<td>{{$row->m_korcam->nama_korcam}}</td>
									<td class="text-center">25</td>
									<td class="text-center">344</td>
									<td class="text-right">24.080.000</td>
									<td class="text-center">
										<a data-toggle="tooltip" data-placement="top" title="edit" href="{{route('app.transaksi.pendaftaran.edit', ['korcam' => $tipe_user])}}" class="btn btn-xs btn-warning" data-toggle="tooltip" data-original-title="Edit"><i class="fa fa-edit"></i></a>
										<a data-toggle="tooltip" data-placement="top" title="kwitansi" href="{{route('app.transaksi.pendaftaran.kwitansi')}}" class="btn btn-xs btn-primary" data-toggle="tooltip" data-original-title="Kwitansi"><i class="fa fa-credit-card"></i></a>
									</td>
								</tr>
							@endforeach
							</tbody>
							<thead>
								<tr>
								  <th class="text-center" colspan="2">Jumlah</th>
								  <th class="text-center">111</th>
								  <th class="text-center">1.313</th>
								  <th class="text-right">91.910.000</th>
								  <th class=""></th>
								</tr>
							</thead>
						</table>

				</div>
                </div>
               
            </div>
            <!-- /.card-body -->
          </div>
         



        <div class="col-md-8">
          
          <div class="card">
            <div class="card-header bg-primary">
              <h3 class="card-title">Rekap</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                	<a href="{{ route('app.transaksi.pendaftaran.index') }}" class="btn btn-{{\Route::currentRouteName() == 'app.transaksi.pendaftaran.index' ? 'primary' : 'default'}} mb-3"><i class="fas fa-list"></i> Rekap Korcam</a>&nbsp;&nbsp;
                	<a href="{{ route('app.transaksi.pendaftaran.rekap_tpq') }}" class="btn btn-{{\Route::currentRouteName() == 'app.transaksi.pendaftaran.rekap_tpq' ? 'primary' : 'default'}} mb-3"><i class="fas fa-list"></i> Rekap TPQ</a>
                	<p></p><br>
                	<table class="table table-bordered table-sm table-striped">
						<thead>
							<tr>
							  <th class="text-center" rowspan="2">No</th>
							  <th class="text-center" rowspan="2">Korcam</th>
							  <th class="text-center" colspan="2">Lembaga</th>
							  <th class="text-center" colspan="3">Peserta</th>
							  <th class="text-center" rowspan="2">Infaq</th>
							  <th class="text-center" rowspan="2">Waktu</th>
							</tr>
							<tr>
							  <th class="text-center">Jml</th>
							  <th class="text-center">Imtas</th>
							  <th class="text-center">Baru</th>
							  <th class="text-center">Ulang</th>
							  <th class="text-center">Jml</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="text-center">1</td>
								<td>01.04.01 Waru</td>
								<td class="text-center">30</td>
								<td class="text-center">25</td>
								<td class="text-center">344</td>
								<td class="text-center">0</td>
								<td class="text-center">344</td>
								<td class="text-right">24.080.000</td>
								<td class="text-center">2021-01-25 07:26:39</td>
							</tr>
						</tbody>
					</table>

                </div>
            </div>
          </div>
        </div>


  </section>
    <!-- /.content -->

				@endsection